# Generated by Django 4.2.2 on 2023-07-15 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('info', models.CharField(default='Hotel_Info', max_length=200)),
                ('score', models.FloatField(default=0, null=True)),
                ('price', models.PositiveIntegerField(default=0, null=True)),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_infoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HotelReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('score', models.FloatField(default=0.0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hotel_booking.hotelinfo')),
            ],
        ),
        migrations.CreateModel(
            name='HotelProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('is_booked', models.IntegerField(default=0)),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='images/products/')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='hotel_booking.hotelinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
