# Generated by Django 4.2.3 on 2023-07-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelinfo',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotelinfo',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
