# Generated by Django 4.2.3 on 2023-07-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelinfo',
            name='hotel_info',
            field=models.CharField(default='Hotel_Info', max_length=200),
        ),
    ]
