# Generated by Django 4.2.3 on 2023-07-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_booking', '0002_hotelproduct_is_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelproduct',
            name='is_booked',
            field=models.IntegerField(default=0),
        ),
    ]
