# Generated by Django 4.2.3 on 2023-07-06 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_booking', '0002_hotelinfo_price_hotelinfo_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelinfo',
            name='price',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hotelinfo',
            name='score',
            field=models.FloatField(default=0, null=True),
        ),
    ]
