# Generated by Django 4.2.3 on 2023-07-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_booking', '0003_alter_hotelproduct_is_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
