# Generated by Django 4.2.3 on 2023-07-12 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_booking', '0010_alter_hotelinfo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelinfo',
            name='image',
        ),
    ]
