# Generated by Django 4.2.3 on 2023-07-13 06:37

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_booking', '0014_alter_hotelinfo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelproduct',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default=1, upload_to='images/products/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotelinfo',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='images/'),
        ),
    ]
