# Generated by Django 4.2.3 on 2023-07-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_book_end_date_remove_book_start_date'),
        ('hotel_booking', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bookings',
            field=models.ManyToManyField(related_name='bookers', through='booking.Book', to='hotel_booking.hotelproduct'),
        ),
    ]
