# Generated by Django 4.2.3 on 2023-07-04 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_user_auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_auth',
        ),
    ]
