# Generated by Django 4.2.3 on 2023-07-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_booking', '0001_initial'),
        ('booking', '0004_remove_book_end_date_remove_book_start_date'),
        ('accounts', '0002_user_bookings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bookings',
        ),
        migrations.AddField(
            model_name='user',
            name='reserved_products',
            field=models.ManyToManyField(related_name='reserved_users', through='booking.Book', to='hotel_booking.hotelproduct'),
        ),
    ]
