# Generated by Django 4.2.3 on 2023-07-06 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='username',
            new_name='name',
        ),
    ]
