# Generated by Django 4.2.3 on 2023-07-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_book_use_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='use_date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='book',
            name='end_date',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
