# Generated by Django 4.2.2 on 2023-07-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_username_book_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
